# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Char字段', models.CharField(max_length=32, verbose_name='Char字段')),
                ('选择字段', models.CharField(blank=True, choices=[('xz1', '选择1'), ('xz2', '选择2'), ('Unkown', '未知')], default='Unkown', max_length=6, null=True, verbose_name='选择字段')),
                ('Decimal字段', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Decimal字段')),
                ('布尔字段', models.BooleanField(default=False, verbose_name='布尔字段')),
                ('时间字段', models.DateTimeField(auto_now_add=True, verbose_name='时间字段')),
                ('整数字段', models.IntegerField(blank=True, default=0, verbose_name='整数字段')),
            ],
            options={
                'verbose_name': '测试数据',
                'verbose_name_plural': '测试数据',
                'ordering': ['-时间字段'],
            },
        ),
    ]
